### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by marcoacierno** [marcoacierno/Slaughterfield-AD-Docker#6]
- [ ] Remove G_ID feature?
- [ ] Add MySQL container
- [ ] Download and execute .sql file to the MySQL container
- [ ] Let the container write the mysql config file with the data to connect to the database
